// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelegramGateway_Invoke_FullMethodName             = "/telefeeds.telegram.v1.TelegramGateway/Invoke"
	TelegramGateway_DownloadBotApiFile_FullMethodName = "/telefeeds.telegram.v1.TelegramGateway/DownloadBotApiFile"
)

// TelegramGatewayClient is the client API for TelegramGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TelegramGatewayClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	DownloadBotApiFile(ctx context.Context, in *BotApiFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BotApiFileChunk], error)
}

type telegramGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewTelegramGatewayClient(cc grpc.ClientConnInterface) TelegramGatewayClient {
	return &telegramGatewayClient{cc}
}

func (c *telegramGatewayClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, TelegramGateway_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegramGatewayClient) DownloadBotApiFile(ctx context.Context, in *BotApiFileRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BotApiFileChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelegramGateway_ServiceDesc.Streams[0], TelegramGateway_DownloadBotApiFile_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BotApiFileRequest, BotApiFileChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramGateway_DownloadBotApiFileClient = grpc.ServerStreamingClient[BotApiFileChunk]

// TelegramGatewayServer is the server API for TelegramGateway service.
// All implementations must embed UnimplementedTelegramGatewayServer
// for forward compatibility.
type TelegramGatewayServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	DownloadBotApiFile(*BotApiFileRequest, grpc.ServerStreamingServer[BotApiFileChunk]) error
	mustEmbedUnimplementedTelegramGatewayServer()
}

// UnimplementedTelegramGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelegramGatewayServer struct{}

func (UnimplementedTelegramGatewayServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedTelegramGatewayServer) DownloadBotApiFile(*BotApiFileRequest, grpc.ServerStreamingServer[BotApiFileChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadBotApiFile not implemented")
}
func (UnimplementedTelegramGatewayServer) mustEmbedUnimplementedTelegramGatewayServer() {}
func (UnimplementedTelegramGatewayServer) testEmbeddedByValue()                         {}

// UnsafeTelegramGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelegramGatewayServer will
// result in compilation errors.
type UnsafeTelegramGatewayServer interface {
	mustEmbedUnimplementedTelegramGatewayServer()
}

func RegisterTelegramGatewayServer(s grpc.ServiceRegistrar, srv TelegramGatewayServer) {
	// If the following call panics, it indicates UnimplementedTelegramGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelegramGateway_ServiceDesc, srv)
}

func _TelegramGateway_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegramGatewayServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TelegramGateway_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegramGatewayServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegramGateway_DownloadBotApiFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BotApiFileRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TelegramGatewayServer).DownloadBotApiFile(m, &grpc.GenericServerStream[BotApiFileRequest, BotApiFileChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelegramGateway_DownloadBotApiFileServer = grpc.ServerStreamingServer[BotApiFileChunk]

// TelegramGateway_ServiceDesc is the grpc.ServiceDesc for TelegramGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelegramGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "telefeeds.telegram.v1.TelegramGateway",
	HandlerType: (*TelegramGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _TelegramGateway_Invoke_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadBotApiFile",
			Handler:       _TelegramGateway_DownloadBotApiFile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
