// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiProtocol int32

const (
	ApiProtocol_API_PROTOCOL_RAW_TL  ApiProtocol = 0
	ApiProtocol_API_PROTOCOL_BOT_API ApiProtocol = 1
)

// Enum value maps for ApiProtocol.
var (
	ApiProtocol_name = map[int32]string{
		0: "API_PROTOCOL_RAW_TL",
		1: "API_PROTOCOL_BOT_API",
	}
	ApiProtocol_value = map[string]int32{
		"API_PROTOCOL_RAW_TL":  0,
		"API_PROTOCOL_BOT_API": 1,
	}
)

func (x ApiProtocol) Enum() *ApiProtocol {
	p := new(ApiProtocol)
	*p = x
	return p
}

func (x ApiProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_proto_enumTypes[0].Descriptor()
}

func (ApiProtocol) Type() protoreflect.EnumType {
	return &file_gateway_proto_enumTypes[0]
}

func (x ApiProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiProtocol.Descriptor instead.
func (ApiProtocol) EnumDescriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

type InvokeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionPeerId int64                  `protobuf:"varint,1,opt,name=session_peer_id,json=sessionPeerId,proto3" json:"session_peer_id,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	DcId          *int32                 `protobuf:"varint,3,opt,name=dc_id,json=dcId,proto3,oneof" json:"dc_id,omitempty"`
	TlLayer       int32                  `protobuf:"varint,4,opt,name=tl_layer,json=tlLayer,proto3" json:"tl_layer,omitempty"`
	Protocol      ApiProtocol            `protobuf:"varint,5,opt,name=protocol,proto3,enum=telefeeds.telegram.v1.ApiProtocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetSessionPeerId() int64 {
	if x != nil {
		return x.SessionPeerId
	}
	return 0
}

func (x *InvokeRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeRequest) GetDcId() int32 {
	if x != nil && x.DcId != nil {
		return *x.DcId
	}
	return 0
}

func (x *InvokeRequest) GetTlLayer() int32 {
	if x != nil {
		return x.TlLayer
	}
	return 0
}

func (x *InvokeRequest) GetProtocol() ApiProtocol {
	if x != nil {
		return x.Protocol
	}
	return ApiProtocol_API_PROTOCOL_RAW_TL
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          []byte                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	RpcError      *TelegramRpcError      `protobuf:"bytes,3,opt,name=rpc_error,json=rpcError,proto3,oneof" json:"rpc_error,omitempty"`
	Protocol      ApiProtocol            `protobuf:"varint,4,opt,name=protocol,proto3,enum=telefeeds.telegram.v1.ApiProtocol" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *InvokeResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *InvokeResponse) GetRpcError() *TelegramRpcError {
	if x != nil {
		return x.RpcError
	}
	return nil
}

func (x *InvokeResponse) GetProtocol() ApiProtocol {
	if x != nil {
		return x.Protocol
	}
	return ApiProtocol_API_PROTOCOL_RAW_TL
}

type TelegramRpcError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         *uint32                `protobuf:"varint,3,opt,name=value,proto3,oneof" json:"value,omitempty"`
	CausedBy      *uint32                `protobuf:"varint,4,opt,name=caused_by,json=causedBy,proto3,oneof" json:"caused_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramRpcError) Reset() {
	*x = TelegramRpcError{}
	mi := &file_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramRpcError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramRpcError) ProtoMessage() {}

func (x *TelegramRpcError) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramRpcError.ProtoReflect.Descriptor instead.
func (*TelegramRpcError) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *TelegramRpcError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *TelegramRpcError) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TelegramRpcError) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *TelegramRpcError) GetCausedBy() uint32 {
	if x != nil && x.CausedBy != nil {
		return *x.CausedBy
	}
	return 0
}

type BotApiFileChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BotApiFileChunk_Header
	//	*BotApiFileChunk_Data
	Payload       isBotApiFileChunk_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotApiFileChunk) Reset() {
	*x = BotApiFileChunk{}
	mi := &file_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotApiFileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotApiFileChunk) ProtoMessage() {}

func (x *BotApiFileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotApiFileChunk.ProtoReflect.Descriptor instead.
func (*BotApiFileChunk) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *BotApiFileChunk) GetPayload() isBotApiFileChunk_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BotApiFileChunk) GetHeader() *BotApiFileHeader {
	if x != nil {
		if x, ok := x.Payload.(*BotApiFileChunk_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *BotApiFileChunk) GetData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*BotApiFileChunk_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isBotApiFileChunk_Payload interface {
	isBotApiFileChunk_Payload()
}

type BotApiFileChunk_Header struct {
	Header *BotApiFileHeader `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type BotApiFileChunk_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*BotApiFileChunk_Header) isBotApiFileChunk_Payload() {}

func (*BotApiFileChunk_Data) isBotApiFileChunk_Payload() {}

type BotApiFileHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionPeerId int64                  `protobuf:"varint,1,opt,name=session_peer_id,json=sessionPeerId,proto3" json:"session_peer_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	ContentType   *string                `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3,oneof" json:"content_type,omitempty"`
	ContentLength *uint64                `protobuf:"varint,4,opt,name=content_length,json=contentLength,proto3,oneof" json:"content_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotApiFileHeader) Reset() {
	*x = BotApiFileHeader{}
	mi := &file_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotApiFileHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotApiFileHeader) ProtoMessage() {}

func (x *BotApiFileHeader) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotApiFileHeader.ProtoReflect.Descriptor instead.
func (*BotApiFileHeader) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *BotApiFileHeader) GetSessionPeerId() int64 {
	if x != nil {
		return x.SessionPeerId
	}
	return 0
}

func (x *BotApiFileHeader) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *BotApiFileHeader) GetContentType() string {
	if x != nil && x.ContentType != nil {
		return *x.ContentType
	}
	return ""
}

func (x *BotApiFileHeader) GetContentLength() uint64 {
	if x != nil && x.ContentLength != nil {
		return *x.ContentLength
	}
	return 0
}

type BotApiFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionPeerId int64                  `protobuf:"varint,1,opt,name=session_peer_id,json=sessionPeerId,proto3" json:"session_peer_id,omitempty"`
	// Types that are valid to be assigned to Source:
	//
	//	*BotApiFileRequest_UploadId
	//	*BotApiFileRequest_TelegramFileId
	Source        isBotApiFileRequest_Source `protobuf_oneof:"source"`
	Offset        *uint64                    `protobuf:"varint,4,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BotApiFileRequest) Reset() {
	*x = BotApiFileRequest{}
	mi := &file_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BotApiFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotApiFileRequest) ProtoMessage() {}

func (x *BotApiFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotApiFileRequest.ProtoReflect.Descriptor instead.
func (*BotApiFileRequest) Descriptor() ([]byte, []int) {
	return file_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *BotApiFileRequest) GetSessionPeerId() int64 {
	if x != nil {
		return x.SessionPeerId
	}
	return 0
}

func (x *BotApiFileRequest) GetSource() isBotApiFileRequest_Source {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BotApiFileRequest) GetUploadId() string {
	if x != nil {
		if x, ok := x.Source.(*BotApiFileRequest_UploadId); ok {
			return x.UploadId
		}
	}
	return ""
}

func (x *BotApiFileRequest) GetTelegramFileId() string {
	if x != nil {
		if x, ok := x.Source.(*BotApiFileRequest_TelegramFileId); ok {
			return x.TelegramFileId
		}
	}
	return ""
}

func (x *BotApiFileRequest) GetOffset() uint64 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type isBotApiFileRequest_Source interface {
	isBotApiFileRequest_Source()
}

type BotApiFileRequest_UploadId struct {
	UploadId string `protobuf:"bytes,2,opt,name=upload_id,json=uploadId,proto3,oneof"`
}

type BotApiFileRequest_TelegramFileId struct {
	TelegramFileId string `protobuf:"bytes,3,opt,name=telegram_file_id,json=telegramFileId,proto3,oneof"`
}

func (*BotApiFileRequest_UploadId) isBotApiFileRequest_Source() {}

func (*BotApiFileRequest_TelegramFileId) isBotApiFileRequest_Source() {}

var File_gateway_proto protoreflect.FileDescriptor

const file_gateway_proto_rawDesc = "" +
	"\n" +
	"\rgateway.proto\x12\x15telefeeds.telegram.v1\"\xca\x01\n" +
	"\rInvokeRequest\x12&\n" +
	"\x0fsession_peer_id\x18\x01 \x01(\x03R\rsessionPeerId\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x18\n" +
	"\x05dc_id\x18\x03 \x01(\x05H\x00R\x04dcId\x88\x01\x01\x12\x19\n" +
	"\btl_layer\x18\x04 \x01(\x05R\atlLayer\x12>\n" +
	"\bprotocol\x18\x05 \x01(\x0e2\".telefeeds.telegram.v1.ApiProtocolR\bprotocolB\b\n" +
	"\x06_dc_id\"\xe2\x01\n" +
	"\x0eInvokeResponse\x12\x12\n" +
	"\x04body\x18\x01 \x01(\fR\x04body\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x12I\n" +
	"\trpc_error\x18\x03 \x01(\v2'.telefeeds.telegram.v1.TelegramRpcErrorH\x01R\brpcError\x88\x01\x01\x12>\n" +
	"\bprotocol\x18\x04 \x01(\x0e2\".telefeeds.telegram.v1.ApiProtocolR\bprotocolB\b\n" +
	"\x06_errorB\f\n" +
	"\n" +
	"_rpc_error\"\x8f\x01\n" +
	"\x10TelegramRpcError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\x05value\x18\x03 \x01(\rH\x00R\x05value\x88\x01\x01\x12 \n" +
	"\tcaused_by\x18\x04 \x01(\rH\x01R\bcausedBy\x88\x01\x01B\b\n" +
	"\x06_valueB\f\n" +
	"\n" +
	"_caused_by\"u\n" +
	"\x0fBotApiFileChunk\x12A\n" +
	"\x06header\x18\x01 \x01(\v2'.telefeeds.telegram.v1.BotApiFileHeaderH\x00R\x06header\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\t\n" +
	"\apayload\"\xcf\x01\n" +
	"\x10BotApiFileHeader\x12&\n" +
	"\x0fsession_peer_id\x18\x01 \x01(\x03R\rsessionPeerId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12&\n" +
	"\fcontent_type\x18\x03 \x01(\tH\x00R\vcontentType\x88\x01\x01\x12*\n" +
	"\x0econtent_length\x18\x04 \x01(\x04H\x01R\rcontentLength\x88\x01\x01B\x0f\n" +
	"\r_content_typeB\x11\n" +
	"\x0f_content_length\"\xb8\x01\n" +
	"\x11BotApiFileRequest\x12&\n" +
	"\x0fsession_peer_id\x18\x01 \x01(\x03R\rsessionPeerId\x12\x1d\n" +
	"\tupload_id\x18\x02 \x01(\tH\x00R\buploadId\x12*\n" +
	"\x10telegram_file_id\x18\x03 \x01(\tH\x00R\x0etelegramFileId\x12\x1b\n" +
	"\x06offset\x18\x04 \x01(\x04H\x01R\x06offset\x88\x01\x01B\b\n" +
	"\x06sourceB\t\n" +
	"\a_offset*@\n" +
	"\vApiProtocol\x12\x17\n" +
	"\x13API_PROTOCOL_RAW_TL\x10\x00\x12\x18\n" +
	"\x14API_PROTOCOL_BOT_API\x10\x012\xd2\x01\n" +
	"\x0fTelegramGateway\x12U\n" +
	"\x06Invoke\x12$.telefeeds.telegram.v1.InvokeRequest\x1a%.telefeeds.telegram.v1.InvokeResponse\x12h\n" +
	"\x12DownloadBotApiFile\x12(.telefeeds.telegram.v1.BotApiFileRequest\x1a&.telefeeds.telegram.v1.BotApiFileChunk0\x01B@Z>github.com/mtgo-labs/mtgo-bot-api/internal/gatewaypb;gatewaypbb\x06proto3"

var (
	file_gateway_proto_rawDescOnce sync.Once
	file_gateway_proto_rawDescData []byte
)

func file_gateway_proto_rawDescGZIP() []byte {
	file_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)))
	})
	return file_gateway_proto_rawDescData
}

var file_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gateway_proto_goTypes = []any{
	(ApiProtocol)(0),          // 0: telefeeds.telegram.v1.ApiProtocol
	(*InvokeRequest)(nil),     // 1: telefeeds.telegram.v1.InvokeRequest
	(*InvokeResponse)(nil),    // 2: telefeeds.telegram.v1.InvokeResponse
	(*TelegramRpcError)(nil),  // 3: telefeeds.telegram.v1.TelegramRpcError
	(*BotApiFileChunk)(nil),   // 4: telefeeds.telegram.v1.BotApiFileChunk
	(*BotApiFileHeader)(nil),  // 5: telefeeds.telegram.v1.BotApiFileHeader
	(*BotApiFileRequest)(nil), // 6: telefeeds.telegram.v1.BotApiFileRequest
}
var file_gateway_proto_depIdxs = []int32{
	0, // 0: telefeeds.telegram.v1.InvokeRequest.protocol:type_name -> telefeeds.telegram.v1.ApiProtocol
	3, // 1: telefeeds.telegram.v1.InvokeResponse.rpc_error:type_name -> telefeeds.telegram.v1.TelegramRpcError
	0, // 2: telefeeds.telegram.v1.InvokeResponse.protocol:type_name -> telefeeds.telegram.v1.ApiProtocol
	5, // 3: telefeeds.telegram.v1.BotApiFileChunk.header:type_name -> telefeeds.telegram.v1.BotApiFileHeader
	1, // 4: telefeeds.telegram.v1.TelegramGateway.Invoke:input_type -> telefeeds.telegram.v1.InvokeRequest
	6, // 5: telefeeds.telegram.v1.TelegramGateway.DownloadBotApiFile:input_type -> telefeeds.telegram.v1.BotApiFileRequest
	2, // 6: telefeeds.telegram.v1.TelegramGateway.Invoke:output_type -> telefeeds.telegram.v1.InvokeResponse
	4, // 7: telefeeds.telegram.v1.TelegramGateway.DownloadBotApiFile:output_type -> telefeeds.telegram.v1.BotApiFileChunk
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gateway_proto_init() }
func file_gateway_proto_init() {
	if File_gateway_proto != nil {
		return
	}
	file_gateway_proto_msgTypes[0].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[1].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[2].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[3].OneofWrappers = []any{
		(*BotApiFileChunk_Header)(nil),
		(*BotApiFileChunk_Data)(nil),
	}
	file_gateway_proto_msgTypes[4].OneofWrappers = []any{}
	file_gateway_proto_msgTypes[5].OneofWrappers = []any{
		(*BotApiFileRequest_UploadId)(nil),
		(*BotApiFileRequest_TelegramFileId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_proto_rawDesc), len(file_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_proto_msgTypes,
	}.Build()
	File_gateway_proto = out.File
	file_gateway_proto_goTypes = nil
	file_gateway_proto_depIdxs = nil
}
